name: Create Release

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  checkVersion:
    if: github.event.pull_request.merged == true
    name: Check package version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check package version
        id: check
        uses: PostHog/check-package-version@v2

      - name: Cancel when unchanged
        uses: andymckay/cancel-action@0.2
        if: steps.check.outputs.is-new-version == 'false'

  create-relase:
    needs: [checkVersion]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check package version
        id: check
        uses: PostHog/check-package-version@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_AUTH_TOKEN }}
        with:
          tag_name: v${{ steps.check.outputs.committed-version }}
          release_name: v${{ steps.check.outputs.committed-version }}
          body: ${{ github.event.pull_request.body }}
          draft: false
          prerelease: false
